import Box from "@mui/material/Box";
import Typography from "@mui/material/Typography";
import Chip from "@mui/material/Chip";
import Table from "@mui/material/Table";
import TableBody from "@mui/material/TableBody";
import TableCell from "@mui/material/TableCell";
import TableHead from "@mui/material/TableHead";
import TableRow from "@mui/material/TableRow";
import { useParams } from "react-router-dom";
import PrintDocShell, { SectionTitle } from "../components/PrintDoc";
import { RagChip } from "../components/RagChip";
import { sectionStatusFor, useAppState } from "../data/store";
import { AREAS_INSPECTED_CHECKLIST, INSPECTION_SECTIONS, RAG_LEGEND } from "../data/seed";
import { fireCurrencyFor, SPACE_STANDARD_M2_PER_PERSON } from "../data/types";
import { brand, rag } from "../theme/tokens";

// The descriptor's "Department return generator": the IPPS inspection
// report structure, pre-filled from the live registers so the operator's
// side of a return (or a self-inspection submission) is one click, not a
// week of transcription.
export default function DeptReturn() {
  const { centreId } = useParams();
  const state = useAppState();

  const centre = state.centres.find((c) => c.id === centreId) ?? state.centres[0];
  const rooms = state.roomsByCentre[centre.id] ?? [];
  const unrecordedRooms = rooms.filter((r) => r.currentOccupancy === null).length;
  const registers = state.registersByCentre[centre.id] ?? [];
  const fireRegisters = state.fireByCentre[centre.id] ?? [];
  const notices = state.noticesByCentre[centre.id] ?? [];
  const findings = state.findings.filter((f) => f.centreId === centre.id);

  return (
    <PrintDocShell
      backTo={`/centres/${centre.id}`}
      backLabel="Back to centre"
      title="Department Return — IPPS Inspection Format"
      subtitle={`${centre.name} · ${centre.accommodationId} · Generated ${new Date().toISOString().slice(0, 10)}`}
      footer="Generated by the Peppard IPAS Operator Dashboard. Every field in this return is drawn from a live register (centre master record, room register, administration registers, findings register); nothing is manually keyed. Format mirrors the Department of Justice IPPS inspection report structure."
    >
      <SectionTitle n={1}>Centre master record</SectionTitle>
      <Table size="small">
        <TableBody>
          {[
            ["Accommodation ID", centre.accommodationId],
            ["Centre name", centre.name],
            ["Address", `${centre.location}, Co. ${centre.county}`],
            ["Centre profile", centre.profile],
            ["General Manager", centre.manager],
            ["Provider contract capacity", String(centre.contractCapacity)],
            [
              "Occupancy (from room register)",
              `${centre.occupancy}${unrecordedRooms ? ` — ${unrecordedRooms} rooms without recorded occupancy` : ""}`,
            ],
            ["Number of rooms", String(rooms.length)],
            ["Last Department inspection", centre.lastIppsInspection ?? "—"],
            ["Fire risk assessment", "Mackin EHS — 2026 H&S audit & FRA programme"],
          ].map(([k, v]) => (
            <TableRow key={k}>
              <TableCell sx={{ fontWeight: 600, width: 260 }}>{k}</TableCell>
              <TableCell>{v}</TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>

      <SectionTitle n={2}>Areas covered by this return</SectionTitle>
      <Box component="ul" sx={{ m: 0, pl: 3 }}>
        {AREAS_INSPECTED_CHECKLIST.map((item) => (
          <Typography component="li" key={item} sx={{ fontSize: "0.85rem", mb: 0.5 }}>
            {item}
          </Typography>
        ))}
      </Box>

      <SectionTitle n={3}>Inspection sections — status derived from live registers</SectionTitle>
      <Typography sx={{ fontSize: "0.8rem", color: "text.secondary", mb: 1 }}>
        Each section's status is computed from the registers, notices and fire records mapped to it — a section reads
        "In order" only when nothing tagged to it needs attention.
      </Typography>
      <Table size="small">
        <TableBody>
          {INSPECTION_SECTIONS.map((title) => {
            const section = sectionStatusFor(title, centre.id, state);
            return (
              <TableRow key={title}>
                <TableCell sx={{ fontWeight: 600 }}>
                  {title}
                  {section.notes.map((note) => (
                    <Typography key={note} sx={{ fontSize: "0.75rem", fontWeight: 400, color: "text.secondary" }}>
                      {note}
                    </Typography>
                  ))}
                </TableCell>
                <TableCell sx={{ width: 190, verticalAlign: "top" }}>
                  {section.status === "in_order" ? (
                    <Chip label="In order" size="small" sx={{ backgroundColor: rag.greenBg, color: rag.green }} />
                  ) : (
                    <Chip label="Attention required" size="small" sx={{ backgroundColor: rag.amberBg, color: rag.amber }} />
                  )}
                </TableCell>
              </TableRow>
            );
          })}
        </TableBody>
      </Table>

      <SectionTitle n={4}>Mandatory public notices</SectionTitle>
      <Table size="small">
        <TableHead>
          <TableRow>
            <TableCell>Notice</TableCell>
            <TableCell sx={{ width: 120 }}>Status</TableCell>
            <TableCell sx={{ width: 200 }}>Last verified</TableCell>
          </TableRow>
        </TableHead>
        <TableBody>
          {notices.map((n) => (
            <TableRow key={n.name}>
              <TableCell>{n.name}</TableCell>
              <TableCell sx={{ color: n.compliant ? rag.green : rag.red, fontWeight: 700 }}>
                {n.compliant ? "Displayed" : "Missing"}
              </TableCell>
              <TableCell sx={{ fontSize: "0.78rem" }}>
                {n.verifiedOn ? `${n.verifiedOn}${n.verifiedBy ? ` · ${n.verifiedBy}` : ""}` : "—"}
              </TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>

      <SectionTitle n={5}>Administration registers</SectionTitle>
      <Table size="small">
        <TableHead>
          <TableRow>
            <TableCell>Register</TableCell>
            <TableCell sx={{ width: 150 }}>Regulatory mapping</TableCell>
            <TableCell sx={{ width: 120 }}>Last reviewed</TableCell>
            <TableCell sx={{ width: 130 }}>Status</TableCell>
          </TableRow>
        </TableHead>
        <TableBody>
          {registers.map((reg) => (
            <TableRow key={reg.name}>
              <TableCell>{reg.name}</TableCell>
              <TableCell sx={{ fontSize: "0.75rem", color: "text.secondary" }}>
                {reg.ippsSection ? `IPPS §${reg.ippsSection}` : ""}
                {reg.ippsSection && reg.hiqaStandard ? " · " : ""}
                {reg.hiqaStandard ? `HIQA ${reg.hiqaStandard}` : ""}
              </TableCell>
              <TableCell>{reg.lastReviewed}</TableCell>
              <TableCell>
                {reg.status === "in_order" ? "In order" : reg.status === "attention" ? "Needs attention" : "Not reviewed"}
              </TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>

      <SectionTitle n={6}>Fire safety register currency</SectionTitle>
      <Table size="small">
        <TableHead>
          <TableRow>
            <TableCell>Register</TableCell>
            <TableCell align="right">Days since last check</TableCell>
            <TableCell align="right">Required every</TableCell>
            <TableCell sx={{ width: 110 }}>Currency</TableCell>
          </TableRow>
        </TableHead>
        <TableBody>
          {fireRegisters.map((reg) => {
            const cur = fireCurrencyFor(reg);
            const label = cur.state === "in_date" ? "In date" : cur.state === "due_soon" ? "Due soon" : "Overdue";
            const color = cur.state === "overdue" ? rag.red : cur.state === "due_soon" ? rag.amber : rag.green;
            return (
              <TableRow key={reg.name}>
                <TableCell>{reg.shortName}</TableCell>
                <TableCell align="right">{cur.daysSince ?? "—"}</TableCell>
                <TableCell align="right">{reg.frequencyDays}d</TableCell>
                <TableCell sx={{ color, fontWeight: 700 }}>{label}</TableCell>
              </TableRow>
            );
          })}
        </TableBody>
      </Table>

      <SectionTitle n={7}>Room-by-room register</SectionTitle>
      <Typography sx={{ fontSize: "0.8rem", color: "text.secondary", mb: 1 }}>
        Suitable occupancy derived at {SPACE_STANDARD_M2_PER_PERSON} m² per person (rooms with varying ceiling height:
        only areas at 2.4 m or higher count).
      </Typography>
      <Table size="small">
        <TableHead>
          <TableRow>
            <TableCell>Room</TableCell>
            <TableCell>Bed config</TableCell>
            <TableCell align="right">Area m²</TableCell>
            <TableCell align="right">Suitable occ.</TableCell>
            <TableCell align="right">Current occ.</TableCell>
            <TableCell>Issues</TableCell>
          </TableRow>
        </TableHead>
        <TableBody>
          {rooms.map((r) => {
            const over = r.currentOccupancy !== null && r.suitableOccupancy !== null && r.currentOccupancy > r.suitableOccupancy;
            return (
              <TableRow key={r.room}>
                <TableCell sx={{ fontWeight: 600 }}>{r.room}</TableCell>
                <TableCell>{r.bedConfig ?? "—"}</TableCell>
                <TableCell align="right">{r.dimensionsM2 ?? "—"}</TableCell>
                <TableCell align="right">{r.suitableOccupancy ?? "—"}</TableCell>
                <TableCell align="right" sx={over ? { color: rag.red, fontWeight: 700 } : undefined}>
                  {r.currentOccupancy ?? "—"}
                </TableCell>
                <TableCell sx={{ fontSize: "0.78rem" }}>{r.issues.join("; ") || "—"}</TableCell>
              </TableRow>
            );
          })}
        </TableBody>
      </Table>

      <SectionTitle n={8}>Summary details — findings & corrective actions</SectionTitle>
      {findings.length === 0 ? (
        <Typography sx={{ fontSize: "0.87rem" }}>No findings recorded.</Typography>
      ) : (
        <Table size="small">
          <TableHead>
            <TableRow>
              <TableCell>Ref</TableCell>
              <TableCell>Finding</TableCell>
              <TableCell>Priority</TableCell>
              <TableCell sx={{ minWidth: 220 }}>Action required</TableCell>
              <TableCell>Evidence attached</TableCell>
              <TableCell sx={{ minWidth: 160 }}>Contractor comment</TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            {findings.map((f, idx) => (
              <TableRow key={f.id}>
                <TableCell>{idx + 1}</TableCell>
                <TableCell sx={{ fontWeight: 600 }}>{f.finding}</TableCell>
                <TableCell>
                  <RagChip priority={f.priority} />
                </TableCell>
                <TableCell sx={{ fontSize: "0.78rem" }}>{f.actionRequired}</TableCell>
                <TableCell>{f.status === "open" ? "No" : "Yes"}</TableCell>
                <TableCell sx={{ fontSize: "0.78rem" }}>{f.evidenceNote ?? "—"}</TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      )}

      <SectionTitle n={9}>RAG legend</SectionTitle>
      <Table size="small">
        <TableBody>
          {Object.entries(RAG_LEGEND).map(([key, desc]) => (
            <TableRow key={key}>
              <TableCell sx={{ width: 100 }}>
                <RagChip priority={key as "RED" | "AMBER" | "GREEN"} />
              </TableCell>
              <TableCell sx={{ fontSize: "0.82rem", color: brand.charcoal }}>{desc}</TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </PrintDocShell>
  );
}
